/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    PdxAreYouSure: typeof import('./src/components/pdx/are-you-sure.vue')['default']
    PdxBaseLayerSlider: typeof import('./src/components/pdx/base-layer-slider.vue')['default']
    PdxBlock: typeof import('./src/components/pdx/block.vue')['default']
    PdxBoardOverlay: typeof import('./src/components/pdx/board-overlay/index.vue')['default']
    PdxBrushSelector: typeof import('./src/components/pdx/brush-selector.vue')['default']
    PdxCellGrid: typeof import('./src/components/pdx/cell-grid.vue')['default']
    PdxDialog: typeof import('./src/components/pdx/dialog/index.vue')['default']
    PdxDialogTitleBar: typeof import('./src/components/pdx/dialog/title-bar.vue')['default']
    PdxEditor: typeof import('./src/components/pdx/editor/index.vue')['default']
    PdxEditorBrushes: typeof import('./src/components/pdx/editor/brushes.vue')['default']
    PdxFileDropdown: typeof import('./src/components/pdx/file-dropdown/index.vue')['default']
    PdxFileDropdownItem: typeof import('./src/components/pdx/file-dropdown/item.vue')['default']
    PdxIcon: typeof import('./src/components/pdx/icon.vue')['default']
    PdxIconToolSelector: typeof import('./src/components/pdx/icon-tool-selector.vue')['default']
    PdxInputNumber: typeof import('./src/components/pdx/input/number.vue')['default']
    PdxInputText: typeof import('./src/components/pdx/input/text.vue')['default']
    PdxInputWrapper: typeof import('./src/components/pdx/input/wrapper.vue')['default']
    PdxJunk: typeof import('./src/components/pdx/junk.vue')['default']
    PdxJunkBuilder: typeof import('./src/components/pdx/junk-builder/index.vue')['default']
    PdxJunkBuilderCanvas: typeof import('./src/components/pdx/junk-builder/canvas.vue')['default']
    PdxJunkColorSelector: typeof import('./src/components/pdx/junk-color-selector.vue')['default']
    PdxJunkEditor: typeof import('./src/components/pdx/junk-editor/index.vue')['default']
    PdxJunkEditorPieceView: typeof import('./src/components/pdx/junk-editor/piece-view.vue')['default']
    PdxJunkEffectBrushSelector: typeof import('./src/components/pdx/junk-effect-brush-selector.vue')['default']
    PdxJunkEffectSelector: typeof import('./src/components/pdx/junk-effect-selector.vue')['default']
    PdxJunkSelectorItem: typeof import('./src/components/pdx/junk-selector-item.vue')['default']
    PdxLayerBase: typeof import('./src/components/pdx/layer/base.vue')['default']
    PdxLayerBrush: typeof import('./src/components/pdx/layer/brush.vue')['default']
    PdxLayerJunk: typeof import('./src/components/pdx/layer/junk.vue')['default']
    PdxLevelBrowser: typeof import('./src/components/pdx/level-browser/index.vue')['default']
    PdxLevelBrowserInput: typeof import('./src/components/pdx/level-browser/input.vue')['default']
    PdxLevelBrowserList: typeof import('./src/components/pdx/level-browser/list.vue')['default']
    PdxLevelBrowserOpenButtons: typeof import('./src/components/pdx/level-browser/open-buttons.vue')['default']
    PdxLevelBrowserSaveButtons: typeof import('./src/components/pdx/level-browser/save-buttons.vue')['default']
    PdxLevelSettings: typeof import('./src/components/pdx/level-settings/index.vue')['default']
    PdxLevelSettingsBannedColor: typeof import('./src/components/pdx/level-settings/banned-color.vue')['default']
    PdxMenuBar: typeof import('./src/components/pdx/menu-bar/index.vue')['default']
    PdxTooltip: typeof import('./src/components/pdx/tooltip.vue')['default']
  }
}
