/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    PdxBaseLayerSlider: typeof import('./src/components/pdx/base-layer-slider.vue')['default']
    PdxBlock: typeof import('./src/components/pdx/block.vue')['default']
    PdxBoardOverlay: typeof import('./src/components/pdx/board-overlay/index.vue')['default']
    PdxBrushSelector: typeof import('./src/components/pdx/brush-selector.vue')['default']
    PdxCellGrid: typeof import('./src/components/pdx/cell-grid.vue')['default']
    PdxEditor: typeof import('./src/components/pdx/editor/index.vue')['default']
    PdxEditorBrushes: typeof import('./src/components/pdx/editor/brushes.vue')['default']
    PdxIcon: typeof import('./src/components/pdx/icon.vue')['default']
    PdxIconToolSelector: typeof import('./src/components/pdx/icon-tool-selector.vue')['default']
    PdxJunk: typeof import('./src/components/pdx/junk.vue')['default']
    PdxJunkBuilder: typeof import('./src/components/pdx/junk-builder/index.vue')['default']
    PdxJunkBuilderCanvas: typeof import('./src/components/pdx/junk-builder/canvas.vue')['default']
    PdxJunkColorSelector: typeof import('./src/components/pdx/junk-color-selector.vue')['default']
    PdxJunkEditor: typeof import('./src/components/pdx/junk-editor/index.vue')['default']
    PdxJunkEditorPieceView: typeof import('./src/components/pdx/junk-editor/piece-view.vue')['default']
    PdxJunkEffectBrushSelector: typeof import('./src/components/pdx/junk-effect-brush-selector.vue')['default']
    PdxJunkEffectSelector: typeof import('./src/components/pdx/junk-effect-selector.vue')['default']
    PdxJunkSelectorItem: typeof import('./src/components/pdx/junk-selector-item.vue')['default']
    PdxLayerBase: typeof import('./src/components/pdx/layer/base.vue')['default']
    PdxLayerBrush: typeof import('./src/components/pdx/layer/brush.vue')['default']
    PdxLayerJunk: typeof import('./src/components/pdx/layer/junk.vue')['default']
    PdxTooltip: typeof import('./src/components/pdx/tooltip.vue')['default']
  }
}
